// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.terzieva.page.domain;

import org.springframework.beans.factory.annotation.Configurable;
import org.terzieva.page.domain.Term;

privileged aspect Term_Roo_Configurable {
    
    declare @type: Term: @Configurable;
    
}
